---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloservice 
spec:
  selector:
    matchLabels:
      app: helloservice
  template:
    metadata:
      labels:
        app: helloservice
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - name: server
        image: ghcr.io/podtato-head/podtatoserver:v0.1.1
        imagePullPolicy: Always
        ports:
        - containerPort: 9000
        env:
        - name: PORT
          value: "9000"
                    
---
apiVersion: v1
kind: Service
metadata:
  name: helloservice
spec:
  selector:
    app: helloservice
  ports:
  - name: http
    port: 9000
    protocol: TCP
    targetPort: 9000
    
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: helloservice
spec:
  host: hello.apps.comcast-1.na-1.rht-labs.com
  port:
    targetPort: http
  tls:
    termination: edge
  to:
    kind: Service
    name: helloservice
    weight: 100
  wildcardPolicy: None
status:
  ingress:
  - conditions:
    host: hello.apps.comcast-1.na-1.rht-labs.com
    routerCanonicalHostname: apps.comcast-1.na-1.rht-labs.com
    routerName: default
    wildcardPolicy: None
